---
title: Jon Chan
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: me@jonhmchan.com
description: I think a lot about code, food, and philosophy.
baseurl: 
url: https://jonchan.io
twitter_username: jonhmchan
github_username: jonhmchan
markdown: kramdown
permalink: "/essays/:title"
